export { default as Navbar } from './Navbar';
export { default as Intro } from './Intro';
export { default as About } from './About';
export { default as Products } from './Products';
export { default as Order } from './Order';
export { default as Gallery } from './Gallery';
export { default as Care } from './Care';
export { default as Contact } from './Contact';
export { default as Footer } from './Footer';